codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - src/main/java/proj/kedabra/billsnap/config/.*
  - src/main/java/proj/kedabra/billsnap/utils/enums/.*
  - src/main/java/proj/kedabra/billsnap/presentation/resources/.*
  - src/main/java/proj/kedabra/billsnap/business/model/.*
  - src/main/java/proj/kedabra/billsnap/BillsnapApplication.java
  - src/main/java/proj/kedabra/billsnap/business/repository/.*


